### ISSUE TITLE
Tabs introduction 

### ISSUE THREAD

**Issue by Chips1234** [MicrosoftEdge/WebViewFeedback#26] opened 2019-06-22 02:28 UTC
It would be nice to have code for tabs. 
Thanks!

**Comment by david-risney** [comment] 2019-06-24 16:40
Thanks for the feedback. Can you elaborate on what you mean? Do you mean you would like to see sample code showing how you might implement browser tabs? Or do you mean something else?

**Comment by verelpode** [comment] 2019-08-19 20:16
Although tabs are an important issue, it seems to me that this is basically the same as issue #6 and the need for WebView2 to support the same ["NewWindowRequested"](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.newwindowrequested) event as WebView 1, while ensuring that temporary/session cookies are available to all tabs/windows/popups (meaning actually all applicable instances of WebView2), especially in the case where cookie handling is complicated by a separate-process mode in WebView2.

**Comment by david-risney** [comment] 2019-09-27 18:15
I think you're right.

Duplicate of #6

**Comment by david-risney** [comment] 2019-09-27 18:16
Duplicate of #6

**Closed by david-risney** 2019-09-27 18:15 UTC
