### ISSUE TITLE
Webview2 not rendering or navigating at all

### ISSUE THREAD

**Issue by kennzhang** [MicrosoftEdge/WebViewFeedback#449] opened 2020-09-17 10:14 UTC
Hi, I've created a very basic project, running WPF dot net 4.8.
Just a very basic one following the example online.

xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
  <wv2:WebView2 x:Name="myWebView" Source="https://www.microsoft.com"/>

webview2 : 0.9.628-prerelease

Earlier stable release doesn't work too. 0.9.622.11

When I run, nothing gets rendered even though the source is pointing to microsoft website.

I've put in the NavigationStarting event, that doesn't seems to get invoked either. Am I missing something?

**Comment by kennzhang** [comment] 2020-09-17 10:30
Ok, it seems like only .Net Core WPF works. Dot net framework 4.8... Any hope on fixing this?

**Comment by kennzhang** [comment] 2020-09-17 13:04
The winforms version doesn't work either. It's even worse, as it's crashing, with the exception "System.NullReferenceException: 'Object reference not set to an instance of an object."
Exception source""Microsoft.Web.WebView2.WinForms"

When system is starting up in the code (Winforms designer generated code: InitializeComponent) this.Controls.Add(this.myWebView);

Any idea if this will be fixed, or when it'll be fixed? Thanks

**Comment by cgeier** [comment] 2020-09-17 13:34
@kennzhang This looks like issue #431. Either use 64-bit (Any CPU with  Prefer 32-bit unchecked or x64) or try the workaround that's posted.

For .NET, you have to use a prerelease version-0.9.622 isn't a prerelease version. See the [Release notes for WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes).

**Comment by kennzhang** [comment] 2020-09-17 14:25
Thank you..

**Comment by champnic** [comment] 2020-09-17 19:15
Closing as a dupe of #431. If those fixes don't help you, please let me know and I can reopen.

**Closed by champnic** 2020-09-17 19:15 UTC
