### ISSUE TITLE
WebView2 - Crashes on Load in C# Winforms application

### ISSUE THREAD

**Issue by krishnanvs11** [MicrosoftEdge/WebViewFeedback#183] opened 2020-05-19 07:58 UTC
I am getting a crash on Load using WebView2. ..NET framework is 4.7.2. I have posted the question in Stackoverflow too, please check and let me know what the issue might be.
https://stackoverflow.com/questions/61885845/microsoft-edge-webview2-sample-crashes-on-load

Tried this sample given by Microsoft as well. It too crashes. 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

Get the this exception trace when I run in Release mode -
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by noxo** [comment] 2020-05-19 15:05
added comment in stackoveflow

**Comment by jpalo** [comment] 2020-05-19 17:12
Looks like WebView2 0.9.515-prerelease does work on Edge 84.0.508.0 Dev in some cases.

- Simplest WinForms with just WebView2: works on 84.0.508.0 on Windows 10 and on Windows Server 2019
- More complex WinForms with multiple WebBrowser controls (just replaced few of them with WebView2 to test) on 84.0.508.0 and on 84.0.519.0 works on Windows 10, but crashes on Windows Server 2019.

```
Application: Taulu.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(System.EventArgs)
   at System.Windows.Forms.Control.AssignParent(System.Windows.Forms.Control)
   at System.Windows.Forms.Control+ControlCollection.Add(System.Windows.Forms.Control)
   at System.Windows.Forms.Form+ControlCollection.Add(System.Windows.Forms.Control)
   at Taulu.ScrollerForm.InitializeComponent()
   at Taulu.ScrollerForm..ctor()
   at Taulu.Program.Main()
```

**Comment by david-risney** [comment] 2020-05-20 16:59
@krishnanvs11, I'm sorry you're hitting this issue. Thanks for reporting it! Can you say which versions of the Edge browser you have installed? Also can you confirm its not the issues other folks have hit #179 where the Edge browser user data folder is set by policy and breaks webview, or #182 where our nuget package is copying the wrong CPU arch webview2loader.dll for 64bit .NET apps?

@jpalo, can you confirm that the issue is only on WS2019 and only publishing your ClickOnce app? You don't see the crash otherwise? I'm not too familiar with ClickOnce apps. Do you know of any differences between publishing vs copy & pasting? It sounds like we'll need to get more familiar with ClickOnce.

**Comment by krishnanvs11** [comment] 2020-05-20 18:54
Hello David,

From what I see, it does not seem to be the same issues as you listed. I get this runtime exception while trying to run a simple form with WebView2 control, in Visual Studio 2019 Community Edition (Version 16.5.5) and .NET framework (4.7.03062). Edge version is 81.0.416.77 (Official build) (64-bit).

Am facing one more issue - I could get it to run using MtrDev.WebView2.WinForms (by Michael Russin) but the deployment package is not including "WebView2Loader.dll". 
a) I added it on manually, created the .msi and installed on my laptop (Windows 8.1, having Visual Studio 2019) and it works. BUT
b) If I deploy the same .msi on a Windows 10 having (Microsoft Build Engine version 4.8.3752.0 and .NET Framework 4.0.30319.42000), the app has some internal error that is suppressed. It causes UI rendering of the WebView2 to stop.

Please let me know the runtime DLLs that I need to pack along with the installer package.

Regards,
Krishnan
     On Wednesday, May 20, 2020, 10:29:34 PM GMT+5:30, David Risney <notifications@github.com> wrote:  
 
 


@krishnanvs11, I'm sorry you're hitting this issue. Thanks for reporting it! Can you say which versions of the Edge browser you have installed? Also can you confirm its not the issues other folks have hit #179 where the Edge browser user data folder is set by policy and breaks webview, or #182 where our nuget package is copying the wrong CPU arch webview2loader.dll for 64bit .NET apps?

@jpalo, can you confirm that the issue is only on WS2019 and only publishing your ClickOnce app? You don't see the crash otherwise? I'm not too familiar with ClickOnce apps. Do you know of any differences between publishing vs copy & pasting? It sounds like we'll need to get more familiar with ClickOnce.

**Comment by MysteriousGreenBean** [comment] 2020-05-21 06:39
Hi,

I want to add here that issue is not WS2019 specific. I have the same problem on Windows10.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at Netcompany.CCM.Outlook.SaveToCase.Forms.BaseForm.WndProc(Message& m)

Visual Studio 2017 15.9.20
W10 Version 2004 (OS Build 19041.113) 64-bit

Currently on the machine I have installed Canary Edge (84.0.521.0), Dev Edge (84.0.516.1) and public version (81.0.416.77). I started from public and after issue occured I installed Dev, and Canary when it still didn't work.

It doesn't seem to be a webview2loader.dll issue - after I saw this thread I tried copying the 64-bit loader (as I'm running 64-bit application) to the output folder and it didn't change anything in the behaviour.

If this is of any relevance - I'm trying to run it as part of VSTO Outlook Add-in

**Comment by gpltaylor** [comment] 2020-05-25 15:47
I had the same issue but fixed by installing canary&version=84.0.524.0.. 

Originally I had...
Edge (44.18362.449.0)
Win10 - 1903

It felt that the object was running some async work that didn't run in time. Therefore adding the Control to the main windows errored.. 
The odd part is, if I reset my break point, the code would continue to run over the raised code without the error. (winform2.Visible = true; / Controls.add(winform2))
However, it never rendered. 

I updated to Version Edge 83.0.478.37 (Official build) (64-bit) but still no luck.

I then updated to canary version=84.0.524.0 and boom it works!

**Comment by krishnanvs11** [comment] 2020-05-25 19:24
That is great. I found out now that it works with Edge Dev too (v 84.0.516.*). But facing a new issue now - even when I use Edge Dev browser directly to join a Jitsi conference (https://meet.jit.si), none of my open windows are visible in the list to do Screen share. Works fine with Firefox but not with Edge or Chrome.
     On Monday, May 25, 2020, 09:17:32 PM GMT+5:30, Garry Taylor <notifications@github.com> wrote:  
 
 


I had the same issue but fixed by installing canary&version=84.0.524.0..

Originally I had...
Edge (44.18362.449.0)
Win10 - 1903

It felt that the object was running some async work that didn't run in time. Therefore adding the Control to the main windows errored..
The odd part is, if I reset my break point, the code would continue to run over the raised code without the error. (winform2.Visible = true; / Controls.add(winform2))
However, it never rendered.

I updated to Version Edge 83.0.478.37 (Official build) (64-bit) but still no luck.

I then updated to canary version=84.0.524.0 and boom it works!

**Comment by kiewic** [comment] 2020-05-25 19:47
The error should clearly indicate that the expected version of Edge is not installed.

**Comment by FRsyesCD** [comment] 2020-05-26 12:14
i guess these guys found something
https://github.com/MicrosoftDocs/edge-developer/issues/686
i will try it even if it doesn't work we can investigate more with them to know what's they have done to get it work

**Comment by FRsyesCD** [comment] 2020-05-26 13:33
this is the solution for that problem :
https://github.com/MicrosoftEdge/WebViewFeedback/issues/213#issuecomment-634026733

**Comment by champnic** [comment] 2020-06-23 00:43
@krishnanvs11 It sounds like the original issue here was resolved by using the correct browser version for your SDK. More info here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning

If that did not fix your original issue, please reopen this.
If you have a different issue, please open a new issue and we'll take a closer look.

Thanks!

**Closed by champnic** 2020-06-23 00:43 UTC
Labels: .NET, bug
