### ISSUE TITLE
WebView1 - callee is not available.

### ISSUE THREAD

**Issue by mjkkirschner** [MicrosoftEdge/WebViewFeedback#109] opened 2020-01-24 00:39 UTC
Hello - I wanted to bring this use case and issue to your attention to potentially see if the same issue would occur in webView2 - we would very much like to have webView2 as an option instead of relying on `system.controls.webBrowser` - which works in the same context as described in that issue.

https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/223

**Comment by david-risney** [comment] 2020-01-24 17:42
Thanks. We're working on .NET support currently. Can you elaborate on how to make this bug occur so we can ensure its not a problem for WebView2?

**Comment by mjkkirschner** [comment] 2020-01-28 16:42
@david-risney - this occurred for me when trying to create a `WebView` from an addin(plugin) for Autocad.

I have not yet found a simpler reproducible case.

**Comment by pagoe-msft** [comment] 2020-01-28 18:41
Hi mjkkirschner,

We are committed to making WebView2 as bug-free as possible. I'll circle back to this thread once we release the .NET preview - and we'd appreciate it if you could try to reproduce your scenario then. 

There are differences in the architecture of WebView2, WebView, and the Browser Control, so because an issue with WebView or the Browser Control does not necessarily mean there will be an issue with WebView2.

**Comment by champnic** [comment] 2020-08-21 05:22
@mjkkirschner Our .NET controls are available. Please give them a try! If you run into a bug, please open a new issue with details. Thanks!
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

**Closed by champnic** 2020-08-21 05:22 UTC
Labels: .NET, bug
