### ISSUE TITLE
Exception occurring during finalizer after a form is closed with WebView2 in it

### ISSUE THREAD

**Issue by MatthewBeardmore** [MicrosoftEdge/WebViewFeedback#246] opened 2020-06-05 15:09 UTC
I am running into the following exception being thrown on the finalizer thread crashing my application after closing a Window that was running a WinForms WebView2 control.

System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.WinForms.WebView2.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

**Comment by pagoe-msft** [comment] 2020-06-09 16:27
@MatthewBeardmore 

Thanks for the feedback, I've filed a bug in our system.

**Comment by oggy22** [comment] 2020-07-02 22:08
Hi Matthew, sorry for the later response!

This exception normally gets thrown if you try to access `CoreWebView2` from non-UI thread (i.e. the thread that didn't create the control). Having this exception thrown from the finalizer is odd. Can you please answer the following questions:
- What's the nuget package version?
- Is there anything peculiar you are doing with the control, initialization and clean-up?
- Are you using NET framework or .NET Core? What version?

-Ogi

**Comment by MatthewBeardmore** [comment] 2020-07-03 01:52
Hi, that’s perfectly fine!

* I am using the 0.9.915 prerelease package as the newer one is missing WinForms. Edge is the latest Developer channel. 
* I am not doing anything special that I can see. I’m creating the form as a sub form from another windows form using ShowDialog(parentWindow). The form itself only has the web view docked with fill. Once the form is closed, the dialog result is returned and the sub form has Dispose() called. 
* I am using .NET Core 3.1 latest runtime 3.1.5.

**Comment by ajmalanwari** [comment] 2020-07-06 18:29
@oggy22  i am having the same issue as well.

- i am using 0.9.538 prerelease package. (Edge is the latest Developer channel).
- I am also not doing anything special, just calling my subform as "new form2().showdialog();"
- I am using .Net Framework 4.7.2

**Comment by oggy22** [comment] 2020-07-21 20:22
Thank you both! I reproed it. We may need to do some more stuff in Dispose()/finilizer.

**Comment by RussKie** [comment] 2020-07-29 05:56
The root cause here is that you're not disposing the webview2 control, which under the hood is dependent on a COM object. Since the COM object is STA, x-thread access (from a GC thread) leads to the failure.
But the error is certainly confusing.

**Comment by champnic** [comment] 2020-08-07 00:05
Some extra info:
Typically calling Form.Close() will call Dispose on children, but only if you call Form.Show(). If you use Form.ShowDialog(), the form will not call Dispose on children when closing. This is why you'll need to call WebView2.Dispose() yourself, probably in FormClosing or before closing the form.

**Closed by champnic** 2020-08-07 00:05 UTC
Labels: .NET, WinForms, bug
