### ISSUE TITLE
Need  A strongly-named assembly .

### ISSUE THREAD

**Issue by Sanjay-Confidosoft** [MicrosoftEdge/WebViewFeedback#216] opened 2020-05-26 09:49 UTC
Hi there,

As per [link](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms).
I am trying to use following nuget package for  Windows Forms. https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.515-prerelease

I am getting following error:
System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.Web.WebView2.WinForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

Is it possible to get strongly-named assembly for 0.9.515-prerelease ?

Thanks,
Sanjay.

**Comment by ukandrewc** [comment] 2020-05-26 11:01
Have you referenced both core and winforms dlls in your project?

**Comment by Sanjay-Confidosoft** [comment] 2020-05-26 12:32
Yes, it's working in test project where .snk file is not included. As soon as I add .snk file to sign the generated assembly it's throw above run time error.

**Comment by ukandrewc** [comment] 2020-05-26 12:49
Aha, I see.

**Comment by david-risney** [comment] 2020-05-26 16:18
Yes, we need to investigate strong name assemblies. Thanks.

**Comment by david-risney** [comment] 2020-05-26 16:19
Duplicate of #181

**Closed by david-risney** 2020-05-26 16:19 UTC
Labels: bug, duplicate
