### ISSUE TITLE
WebView2 runtime (msedgewebview2.exe) will be crashed when opening a new window via window.open

### ISSUE THREAD

**Issue by ms-yuhara** [MicrosoftEdge/WebViewFeedback#423] opened 2020-09-07 05:36 UTC
**Description**
WebView2 runtime (msedgewebview2.exe) will be crashed when opening a new window via window.open.
That occurs only if I handled a NewWindowRequested event and created a new instance of WebView2 to open the page in my app's own window instead of the Edge's window.

**Version**
SDK: 0.9.579-prerelease
Runtime: Confirmed with Beta 85.0.564.44 and Canary 87.0.630.0
Framework: WPF, WinForms
OS: Windows 10 2004 / 1909

**Repro Steps**
1. Extract the attached repro, [SimpleWebView2.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5181186/SimpleWebView2.zip)
2. Launch SimpleWebView2.exe and click the [Navigate] button
3. Click the [Open Popup Window] link and see whether a child page will be opened properly

Expected result: msedgewebview2.exe will **not** be crashed and a child page will be opened properly
Actual result: msedgewebview2.exe will be crashed and a child page will not be able to opened

[AB#29232794](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29232794)

**Comment by cgeier** [comment] 2020-09-07 21:51
You didn't specify what error you received. One error I noticed was "The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)". You need to initialize CoreWebView2 before using it by calling "EnsureCoreWebView2Async" as specified in [Getting started with WebView2 in Windows Forms apps (Preview)](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms).

Here's a modified version of your code:
[SimpleWebView2 4.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5184934/SimpleWebView2.4.zip)

You didn't go into much detail about what you're trying to accomplish, so the modified code is only slightly modified and may not perform as desired.  You'll notice that I've commented out `e.NewWindow = ((Form1)s).webView2.CoreWebView2;` in CoreWebView2_NewWindowRequested. This line causes issues. 

**Remaining issue**: If the following line of code `e.NewWindow = ((Form1)s).webView2.CoreWebView2;` is uncommented, you'll see the error message: "The group or resource is not in the correct state to perform the requested operation." after "Open Popup Window" is clicked. You'll also notice that the text (html) no longer exists on the first/main form after "Open Popup Window" is clicked.

**To reproduce:** 

- Uncomment `e.NewWindow = ((Form1)s).webView2.CoreWebView2;` in CoreWebView2_NewWindowRequested
- Run the program: Debug => Start Debugging
- Click Open Popup Window
- On the first/main Form1 window, click Navigate

**Comment by ms-yuhara** [comment] 2020-09-08 01:50
Thanks @cgeier. I believe setting a new instance of WebView2 to e.NewWindow is an appropriate approach that is described in https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#add_newwindowrequested.

That error (HRESULT: 0x8007139F) you confirmed is a side-effect of this problem. The problem is crashing of msedgewebview2.exe. If you watch processes in the task manager, you will see msedgewebview2.exe is gone when opening a child window.

![msedgewebview2](https://user-images.githubusercontent.com/38028987/92424830-5c227b80-f1c0-11ea-99a5-b5b1b2f3c23f.png)

After that, you can find like the following one in the Application event log.

```
Fault bucket 2255192757322764160, type 5
Event Name: crashpad_exp
Response: Not available
Cab Id: 0

Problem signature:
P1: msedgewebview2.exe
P2: 85.0.564.44
P3: msedge.dll
P4: 85.0.564.44
P5: 16301508
P6: browser
P7: 0xc0000005
P8: 0
P9: 
P10: 
```

**Comment by champnic** [comment] 2020-09-12 05:17
This is a dupe of #293. This is fixed in Edge 86.0.613.0+. You can see your app is using 85.0.564.44. A new Beta was just released, so you shouldn't see this anymore. Your sample app runs correctly on my machine. Thanks!

**Closed by champnic** 2020-09-12 05:17 UTC
Labels: bug

**Comment by cgeier** [comment] 2020-09-13 21:10
@ms-yuhara It looks like some of the code that I posted was flawed. InitializeCoreWebView2Async should be "Task" not "void". Then it needs to be called with "await": `await InitializeCoreWebView2Async();`

Instead of:
```
private void Form1_Load(object sender, EventArgs e)
{
   ...
}
```

It should be
```
private async void Form1_Load(object sender, EventArgs e)
{
   //initialize CoreWebView2
   await InitializeCoreWebView2Async();
}
```

Instead of:
```
public async void InitializeCoreWebView2Async()
{
    //wait for CoreWebView2 initialization
    await webView2.EnsureCoreWebView2Async();
}
```

It should be:
```
public async Task InitializeCoreWebView2Async()
{
    //wait for CoreWebView2 initialization
    await webView2.EnsureCoreWebView2Async();
}
```

Here's the code with the corrections mentioned that I mentioned: [SimpleWebView2_5.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5215093/SimpleWebView2_5.zip)

**Comment by ms-yuhara** [comment] 2020-09-14 01:00
@cgeier Thanks again! BTW, it seems that we can implicitly initialize the CoreWebView2 just by setting the Source property. It is described in https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-webview2.

> Upon creation, the control's CoreWebView2 property will be null. This is because creating the CoreWebView2 is an expensive operation which involves things like launching Edge browser processes. There are two ways to cause the CoreWebView2 to be created: 1) Call the EnsureCoreWebView2Async method. This is referred to as explicit initialization. 2) Set the Source property (which could be done from markup, for example). This is referred to as implicit initialization. Either option will start initialization in the background and return back to the caller without waiting for it to finish. To specify options regarding the initialization process, either pass your own CoreWebView2Environment to EnsureCoreWebView2Async or set the control's CreationProperties property prior to initialization.

**Comment by cgeier** [comment] 2020-09-14 02:33
Yes you can. However, I believe that the folder of the executable will be used to create a web cache folder. If you install your application to %ProgramFiles% or %ProgramFiles(x86)% your application probably won't work.

See #383, #340, #324, and #203

**Comment by champnic** [comment] 2020-09-14 04:24
@cgeier is correct. You can also look at setting [WebView2.CreationProperties](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-corewebview2creationproperties) and giving it a UserDataFolder which will be used during implicit initialization when the WebView2.Source property gets set.

**Comment by ms-yuhara** [comment] 2020-09-14 04:40
@champnic Back to the original problem, yes, the crash itself was resolved with the latest Beta (86.0.622.11). However, my sample isn't working perfectly yet. It does not crash, but no content is output to the child window.

![WebView2](https://user-images.githubusercontent.com/38028987/93044241-32b99200-f68f-11ea-9864-f6177827760f.png)

In Edge, the output is as follows.

![Edge](https://user-images.githubusercontent.com/38028987/93044313-60064000-f68f-11ea-8505-68406b692256.png)

**Comment by cgeier** [comment] 2020-09-14 15:22
@ms-yuhara I looked at your original code again. I've tested three different versions that seem to work, depending on your desired behavior.

### Version 1: 
***Note:** This version intercepts Javascript window.open, and opens another Form1. `e.handled = true;`  stops the MS Edge popup window from opening.

**Original:**
```
private void Form1_Load(object sender, EventArgs e)
{
    webView2.Source = new Uri("about:blank");
}
```

**Updated:** Change Source from `new Uri("about:blank")` to `new Uri(textBox1.Text)`

```
private void Form1_Load(object sender, EventArgs e)
{
    webView2.Source = new Uri(textBox1.Text);
}
```

**Original:**
```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    Microsoft.Web.WebView2.Core.CoreWebView2Deferral deferral = e.GetDeferral();
    Form1 child = new Form1();

    child.WebViewFirstInitialized += (s, args) => {
        e.NewWindow = ((Form1)s).WebView2.CoreWebView2;
        e.Handled = true;
        deferral.Complete();
    };

    child.SetAsChild();
    child.Show();
    }
}
```

**Updated:** Move `e.Handled = true;` and `deferral.Complete();` outside of the event handler.
```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    Microsoft.Web.WebView2.Core.CoreWebView2Deferral deferral = e.GetDeferral();
    Form1 child = new Form1();

    child.WebViewFirstInitialized += (s, args) => {
        e.NewWindow = ((Form1)s).WebView2.CoreWebView2;
    };

    e.Handled = true;
    deferral.Complete();

    child.SetAsChild();
    child.Show();
    }
}
```


***Note**: The other methods remain the same.

Here's the demo:  [SimpleWebView2 - v1.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5219376/SimpleWebView2.-.v1.zip)


### Version 2: 
***Note:** This version behaves the same as opening the URL in MS Edge -- a popup window opens. (although the window size doesn't seem correct). Remove all the code from CoreWebView2_NewWindowRequested--there's no need to use CoreWebView2_NewWindowRequested. 

**Original:**
```
private void Form1_Load(object sender, EventArgs e)
{
    webView2.Source = new Uri("about:blank");
}
```

**Updated:** Change Source from `new Uri("about:blank")` to `new Uri(textBox1.Text)`
```
private void Form1_Load(object sender, EventArgs e)
{
    webView2.Source = new Uri(textBox1.Text);
}
```

**Original:**
```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    Microsoft.Web.WebView2.Core.CoreWebView2Deferral deferral = e.GetDeferral();
    Form1 child = new Form1();

    child.WebViewFirstInitialized += (s, args) => {
        e.NewWindow = ((Form1)s).WebView2.CoreWebView2;
        e.Handled = true;
        deferral.Complete();
    };

    child.SetAsChild();
    child.Show();
    }
}
```

**Updated:** Remove all code from CoreWebView2_NewWindowRequested.
```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    
}
```


***Note**: The other methods remain the same.

Here's the demo:  [SimpleWebView2 - v2.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5219378/SimpleWebView2.-.v2.zip)


### Version 3: 
***Note:** This version combines the behavior of Version 1 and Version 2. While Javascript window.open is intercepted, it isn't marked as handled (e.handled is false), so a new Form1 window is opened as well as a MS Edge popup window.

**Original:**
```
private void Form1_Load(object sender, EventArgs e)
{
    webView2.Source = new Uri("about:blank");
}
```

**Updated:** Change Source from `new Uri("about:blank")` to `new Uri(textBox1.Text)`
```
private void Form1_Load(object sender, EventArgs e)
{
    webView2.Source = new Uri(textBox1.Text);
}
```

**Original:**
```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    Microsoft.Web.WebView2.Core.CoreWebView2Deferral deferral = e.GetDeferral();
    Form1 child = new Form1();

    child.WebViewFirstInitialized += (s, args) => {
        e.NewWindow = ((Form1)s).WebView2.CoreWebView2;
        e.Handled = true;
        deferral.Complete();
    };

    child.SetAsChild();
    child.Show();
    }
}
```

**Updated:** Move `e.Handled = true;` and `deferral.Complete();` outside of the event handler.
```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    Microsoft.Web.WebView2.Core.CoreWebView2Deferral deferral = e.GetDeferral();
    Form1 child = new Form1();

    child.WebViewFirstInitialized += (s, args) => {
        e.NewWindow = ((Form1)s).WebView2.CoreWebView2;
    };

    e.Handled = false; //default value is false, so this line of code can be removed
    deferral.Complete();

    child.SetAsChild();
    child.Show();
    }
}
```


***Note**: The other methods remain the same.

Here's the demo:  [SimpleWebView2 - v3.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5219381/SimpleWebView2.-.v3.zip)

**Comment by ms-yuhara** [comment] 2020-09-14 15:50
@cgeier Thank you but neither version meets the requirements. The following must be met:

1. The child page must be opened in my app's own window instead of the Edge's window
2. The output of the child page must be same as the result in Edge

![Edge](https://user-images.githubusercontent.com/38028987/93044313-60064000-f68f-11ea-8505-68406b692256.png)

**Comment by cgeier** [comment] 2020-09-14 19:50
@ms-yuhara Do you need a child window? Or do you just want to display the "Popup Window" HTML in your apps window. If you just want to display the popup window HTML in your application, in window.open you can change the second parameter from "mywindow" to "_self".

**Original:**
my_window = window.open("",
  "mywindow","status=1,width=350,height=150");

**Updated:**
my_window = window.open("",
  "_self","status=1,width=350,height=150");

**Comment by cgeier** [comment] 2020-09-14 21:11
For requests for help with code, it's probably better to post on StackOverflow. Someone asked about using NewWindowRequested in the following post: [Create tabs using WebView2 - Edge](https://stackoverflow.com/questions/62799506/create-tabs-using-webview2-edge)
