### ISSUE TITLE
Cannot create new host in response to call via remote object 

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebViewFeedback#144] opened 2020-03-24 10:48 UTC
Our host applications has a legacy COM-api where you can display modal HTML-dialogs. Calling any of these methods from an embedded WebView2 via remote object does not work The call CreateCoreWebView2Host succeeds but the callback is not triggered until the call via remote object returns.

Also, once the callback i triggered both window and environment is lost, resulting in a crash.

[AB#28922311](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28922311)

**Comment by david-risney** [comment] 2020-03-24 21:33
Thanks again for trying out AddRemoteObject!

It sounds like for the first issue, it is [how WebView2 does callbacks](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#threading-model):
> Callbacks including event handlers and completion handlers execute serially. That is, if you have an event handler running and begin a message loop no other event handlers or completion callbacks will begin executing reentrantly.

For the second issue, are you holding on to a reference to the host object and environment object in something outside of that callback? Or else, can you share the code for that callback?

**Comment by pontusn** [comment] 2020-03-24 22:21
Ok, so the first issue is by design? Even if it is two separate WebView2 instances? Kind of criples our options for replacing old WebBrowser component where this is a common scenario when both main UI and modal dialogs are implemented with embedded HTML. 

I hold reference to the environment in the containing class, but never get any reference to the host before the application crash.

David Risney <notifications@github.com> skrev: (24 mars 2020 22:34:03 CET)
>Thanks again for trying out AddRemoteObject!
>
>It sounds like for the first issue, it is [how WebView2 does
>callbacks](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#threading-model):
>> Callbacks including event handlers and completion handlers execute
>serially. That is, if you have an event handler running and begin a
>message loop no other event handlers or completion callbacks will begin
>executing reentrantly.
>
>For the second issue, are you holding on to a reference to the host
>object and environment object in something outside of that callback? Or
>else, can you share the code for that callback?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MicrosoftEdge/WebViewFeedback/issues/144#issuecomment-603516734

-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by david-risney** [comment] 2020-03-25 18:57
The first issue is by design. You can still have more than one WebView2 and blocking modal dialogs, but you can't run the modal dialog during a WebView2 callback.

For the second issue, you mean you have an existing environment and you are trying to create a new CoreWebView2 but it crashes before completing? Can you share what your code looks like there?

**Comment by pontusn** [comment] 2020-03-27 10:42
Is there any way to detect that current call is in the context of a callback from WebView2?

**Comment by pontusn** [comment] 2020-03-27 10:43
About second issue I did not yet have time to extract a viable example.

**Comment by champnic** [comment] 2020-08-31 19:41
@pontusn Were you able to figure out the crash? If not, code you share some details, code, and callstack? Thanks!

**Comment by pontusn** [comment] 2020-09-02 04:58
The crash happens when the callback comes to my implemention after the object has been destroyed. 

Currently we work around the issue by initiating modal html-dialogs from a background thread, effectively avoiding the deadlock between callbacks from WebView2.

**Comment by champnic** [comment] 2020-09-03 04:04
Thanks for the update! I'm going to close this issue as it's mostly By Design and you have a workaround. If you see the crash again or it's blocking your work please reopen. Thanks!

**Closed by champnic** 2020-09-03 04:04 UTC
Labels: bug
