### ISSUE TITLE
Bug: when script tag have type module - charset is ignored.

### ISSUE THREAD

**Issue by bsld** [MicrosoftEdge/WebViewFeedback#395] opened 2020-08-19 07:35 UTC
Consider this script tag:

`<script charset="UTF-16" src="register.js" type="module"></script>`

If said file is in UTF-16 encoding it will still be encoded in UTF-8 giving parsing errors. 

If you remove the `type="module"` from the tag it would load fine.

**Comment by champnic** [comment] 2020-08-19 19:54
Hey @bsld, does this repro in the Edge browser as well? Or only when using WebView2?

**Comment by bsld** [comment] 2020-08-20 04:02
@champnic It seems to have been reproducible in Edge too.

**Comment by champnic** [comment] 2020-08-20 04:32
Thanks for checking! It sounds like that behavior is By Design according to the Web Standard for <script>. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

> type
This attribute indicates the type of script represented. The value of this attribute will be in one of the following categories:
module: Causes the code to be treated as a JavaScript module. The processing of the script contents is not affected by the charset and defer attributes.

It looks like charset is also being deprecated:
> Deprecated attributes
charset 
If present, its value must be an ASCII case-insensitive match for "utf-8". It’s unnecessary to specify the charset attribute, because documents must use UTF-8, and the script element inherits its character encoding from the document.

Hope this helps!

**Closed by champnic** 2020-08-20 04:32 UTC
