### ISSUE TITLE
CreateWebView2Environment fails with error HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by raghu038** [MicrosoftEdge/WebViewFeedback#13] opened 2019-05-14 08:25 UTC
I am calling function CreateWebView2Environment in win32 sample application and getting error HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND). 
What could be the reason?

Installed MS Edge(Chromium) Version 76.0.152.0 (Official build) dev (64-bit).

If possible please provide a working sample win32 application.

**Comment by liminzhu** [comment] 2019-05-14 17:21
Thanks for opening the issue @raghu038 ! This probably comes from the WebView loader failing to find the relevant DLLs from the browser. The dev version you installed should be fine. May I ask how and where you installed Edge Dev channel?

**Comment by raghu038** [comment] 2019-05-15 02:15
This is my installation path
"C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe"

I also used function "CreateWebView2EnvironmentWithDetails" after copying folder "C:\Program Files (x86)\Microsoft\Edge Dev\Application\76.0.152.0" to my project folder but getting same error.

**Comment by liminzhu** [comment] 2019-05-15 18:01
That looks correct. Another potential root cause is CPU arch mismatch. Can you check if you're building an x86 app on a x64 machine?

**Comment by nmoinvaz** [comment] 2019-05-16 02:29
I encountered the same issue when using x86 version of DLL with-in an x86 app. When I switched to use the x64 version of the DLL with-in an x64 app, it worked. 

For our use case we need to be able to x86 version of the DLL.

**Comment by raghu038** [comment] 2019-05-16 03:59
Yes, I am building x86 app on x64. Our requirement is embedding Edge in 32 bit application. 
Is there any solution for this?

**Comment by raghu038** [comment] 2019-05-16 04:23
I built my sample application as 64bit app and it works. 
But it will not solve our problem as we have a 32 bit application(in which we need to embed Edge). 
And it is not easy to convert our application from 32bit to 64bit due to its complex nature. 
So what other options we have in this case?

**Comment by liminzhu** [comment] 2019-05-16 17:49
Ah I'm glad we at least figure out what the issue is. We're aware that 32-bit WebView doesn't work on 64-bit environment (see https://github.com/MicrosoftEdge/WebViewFeedback/issues/11). This is an issue we are actively looking into and I will share once we have update on that.

**Comment by liminzhu** [comment] 2019-05-16 21:00
Marking this as a duplicate for https://github.com/MicrosoftEdge/WebViewFeedback/issues/11.

**Comment by raghu038** [comment] 2019-05-17 03:56
We are having 32 bit application only and hence we need to create ActiveX control of 32 bit to embed webview2 control into our application. We can't continue to test with 64 bit. So please prioritize this issue and help us in resolving this issue. Without 32 bit, we can't work. With C++ sample application we can't test all our use cases and hence we can't say which APIs are working or not working.

If you can resolve this 32 bit issue, we can continue to test and share feedback regarding APIs.

**Comment by liminzhu** [comment] 2019-05-20 22:37
Gotcha, we're looking into the issue and I will update here once we have a fix.

**Comment by liminzhu** [comment] 2019-06-17 16:29
Thanks for sharing the issue with us folks! This is fixed in the new SDK [update](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08190). Make sure you update the SDK and use the Canary channel for testing since the Dev channel may not have the necessary fix yet.

**Closed by liminzhu** 2019-06-17 16:29 UTC
Labels: duplicate
