### ISSUE TITLE
Question about uninstallation of Runtime

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebViewFeedback#361] opened 2020-08-03 15:55 UTC
On https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2environment#add_newbrowserversionavailable you explain that "It is recommended that the application handles restart manager messages so that it can be restarted gracefully in the case when the app is using Edge for webview from a certain installation and that installation is being uninstalled.".

We are loading the WebView2Loader-DLL dynamically with LoadLibrary/FreeLibrary but we see that WM_ENDSESSION is sent even then we freed the library before (certainly before that the window containing the WebView2 was closed).

Can you verify that WM_ENDSESSION is sent to a host process even if WebView2Loader-DLL was unloaded before?

[AB#28324555](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28324555)

**Comment by liminzhu** [comment] 2020-08-03 17:34
The loader is actually irrelevant here. It is included as part of your app, and not something that gets serviced when a new browser/runtime version is available. As long as all the msedgewebview2.exe processes go away, the next time you create a new WebView environment it will be on the new version.

**Comment by Urmeli0815** [comment] 2020-08-04 09:07
I think you missed my point. Let me reformulate it:
1) My C++-App opens a window with an embedded WebView2
2) I close the window in my app so no WebView2 instance is open anymore (and the WebView2Loader-DLL is unloaded)
3) Now the WebView2-Runtime is uninstalled
4) My App gets a WM_ENDSESSION message and exits because of that

Question if this WM_ENDSESSION is necessary what the App doesn't have a WebView2-Control open.

**Comment by liminzhu** [comment] 2020-08-10 18:51
//+@champnic 

Oh interesting, you're saying your app gets a WM_ENSESSION message when WV Runtime gets uninstalled right? This sounds like a bug we should look into.

**Comment by champnic** [comment] 2020-08-10 19:32
Have you verified that the browser processes that your app created have shut down before you try uninstalling? You can typically see this in Task Manager to verify.
Are you calling ICoreWebView2Controller::Close() explicitly, or are you making sure that the CoreWebView2Controller is getting cleaned up (and calling Close itself)? https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2controller#close

If there is no running browser instance, then it would be a bug that we are sending WM_ENDSESSION and we'll fix this.

**Comment by Urmeli0815** [comment] 2020-08-11 07:20
I checked it, there is no msedgewebview2.exe process running when we get WM_ENDSESSION message. The behaviour doesn't change when I call the Close()-Method on the WebView2Controller.

**Comment by champnic** [comment] 2020-08-11 18:48
Thanks for the added info, we'll take a look at this and get it fixed.

**Comment by LiangTheDev** [comment] 2020-08-24 22:59
This is actually by design currently.
When an app ever created WebView, EmbeddedBrowserWebView.dll from the Runtime installation will be loaded into the app's process. That dll will stay loaded in the app process even after all WebViews are closed. FWIW, this dll also map a dat file into the app process.
We don't support unloading of the EmbeddedBrowserWebView.dll. The only way to shutdown is to restart the app. Therefore the app process will have to be restarted when Runtime is uninstalled.

**Closed** 2020-08-25 01:19 UTC
Labels: bug
