### ISSUE TITLE
Could not add the  'Microsoft.Web.WebView2 0.8.230, a reference in C# windows application.

### ISSUE THREAD

**Issue by prasad-yadav** [MicrosoftEdge/WebViewFeedback#46] opened 2019-09-10 10:33 UTC
I have created the C# windows application and install Microsoft.Web.WebView2 0.8.230 dll.
The dll is installed successfully but I haven't found dll in project references.
so I have browser the dll and try to add the dll project but that dll is not added in to project?

please give me some referral answers for this issue.

**Comment by david-risney** [comment] 2019-09-10 17:22
The scenario you describe is not currently supported.  We're working on .NET support (see #23). 

We do have a TLB file in the nuget package. The closest you can get currently is to use tlbimp.exe on the TLB to generate a DLL you can use in .NET. But that won't have support for WPF or WinForms. This is what we're working on building.

**Comment by prasad-yadav** [comment] 2019-09-27 10:04
How much duration will it take to provide support for WebView2 in  .NET WPF or WinForms application.

**Comment by david-risney** [comment] 2019-09-27 17:50
It is a feature we are planning but I'm not sure when we'll finish yet.

**Comment by afshinjafari** [comment] 2019-10-14 01:05
Hi David,
Do you have any update of when this feature will be available?
also, is it possible to dllimport WebView2Loader.dll (and reference dll created using tlbimp) and create viewer control?
cheers,
Afshin

**Comment by david-risney** [comment] 2019-10-14 17:27
Apologies, no update on dates yet.

You could potentially use tlbimp on the tlb from the nuget package. The tlbimp generated DLL can be used to interact with the values returned from the WebView2Loader.dll CreateWebView2Environment method. But you'd likely need to make your own C# wrapper around all that to make a useful sort of WebView2 .NET control. It is doable but will be some work. This is essentially  what we'll be working on to support WebView2 in .NET.

**Comment by afshinjafari** [comment] 2019-10-14 22:09
Hi David,
Thanks for the reply,
Thant's what I'm doing right now, yes it's double but I guess worth the experience,
just one question, (sorry @prasad-yadav for hijacking the thread):
how do I provide _RemotableHandle to CreateWebView method? I guess tlbimp converted Hwnd to this structure and I'm not sure how to convert from/control handle to this structure.

**Comment by david-risney** [comment] 2019-10-14 22:20
Not sure offhand. I would have thought that CreateWebView should take a IntPtr as the first param for its .NET method. Perhaps [this StackOverflow conversation ](https://stackoverflow.com/questions/4077326/tlbimp-exe-converts-hwnd-to-remotablehandle) helps.

**Comment by afshinjafari** [comment] 2019-10-14 23:35
That's what I expect too, however the CreateWebView method generated by tlbimp has this _RemotableHandle  as the first parameter.
I saw that post yesterday, unfortunately the suggestions there are either recompile the com with a switch or the other one (HWNDtoRemotableHandle method) gives me access violation exception.

**Comment by landidavid** [comment] 2019-11-29 09:35
Hello everyone, I find the WebView2 control very useful. Already successfully tested with the example WebView2Sample.

Is it possible to create a WebView2 control for UWP?

I have created an Interop.WebView2.dll from WebView2.tbl via tlbimp. I referenced the Interop.WebView2.dll in UWP and added the Microsoft.Web.WebView2 0.8.230 package via nuget.

Then I created a WebView2 class on UWP that inherits from FrameworkElement and implements IWebView2WebView, IWebView2WebView2, IWebView2WebView3, IWebView2WebView4

Now I have to implement the methods. I tried to define for example the "Navigate" method as follows:

[DllImport ("WebView2Loader.dll", EntryPoint = "Navigate")]
        public static extern void Navigate (string uri);

But at runtime I get the error "System.DllNotFoundException: 'Unable to load DLL' WebView2Loader.dll ': Unable to find the specified module. (Exception from HRESULT: 0x8007007E)'"

Some idea?
Thanks

**Comment by michael-russin** [comment] 2019-11-29 12:21
WebView2Loader.dll doesn't exposes Navigate as as a method you can p/invoke.  You need to create the WebView2 environment, then WebView2 browser then you can navigate.   Creating the environment is p/invoke and the rest is COM interop. 

You can check out some working interop code at [WebView2 Interop](https://github.com/michael-russin/webview2-interop) the nuget package is [here](https://www.nuget.org/packages/MtrDev.WebView2.Interop/) There is a .net version of the browser sample that uses the interop at [DotNetBrowser sample](https://github.com/michael-russin/webview2-dotnetbrowser) Maybe some of that code will help.

**Comment by landidavid** [comment] 2019-11-29 15:52
Thanks Michael for your reply.

I saw your examples and I tested WebView2 Windows Forms control which works very well. I would like to implement a WebView2 Control for a UWP but I can't do p/Invoke on WebView2Loaderdll to create the environment.

I always get an "E_ACCESSDENIED" to the DLL. Are there any limitations on the Universal Windows Platform?

**Comment by david-risney** [comment] 2019-11-29 22:25
We plan to support [a XAML version of WebView2 ](https://github.com/microsoft/microsoft-ui-xaml/issues/1658) that can work in UWP apps. But yes there are limitations on UWP apps that may not work well with our current WebView2Loader.

**Comment by landidavid** [comment] 2019-12-01 07:39
I have the urgency to create in a few days a WebView 2 control for a UWP or any alternative solution that allows me to be able to use Edge-Chromium or Chome from a UWP.

Those interested can contact me privately, we agree to consult.

Thank you all

**Comment by markismail7** [comment] 2019-12-30 01:50
I'm currently using WebView in my .Net Application which emulates Microsoft Edge. When the update rolls out on Jan 15th 2020, Will Edge chromium replaces Microsoft Edge? If that's the case, it will be a problem for our users since we have no access to WebView2 .Net. I am little disappointed on how Microsoft left .Net behind when it comes to edge chromium. We could have contributed so much by testing it. And now the update is rolling out and yet there is no time frame on when .Net will be included. That's a set back for every company using .NET

> Thanks for trying out our SDK! Unfortunately, the scenario you describe is not currently supported. We're working on .NET support (see #23).
> 
> We do have a TLB file in the nuget package. The closest you can get currently is to use tlbimp.exe on the TLB to generate a DLL you can use in .NET. But that won't have support for WPF or WinForms. This is what we're working on building.

I'm currently using WebView in my .Net Application which emulates Microsoft Edge. When the update rolls out on Jan 15th 2020, Will Edge chromium replaces Microsoft Edge? If that's the case, it will be a problem for our users since we have no access to WebView2 .Net. I am little disappointed on how Microsoft left .Net behind when it comes to edge chromium. We could have contributed so much by testing it. And now the update is rolling out and yet there is no time frame on when .Net will be included. That's a set back for every company using .NET

**Comment by liminzhu** [comment] 2020-01-06 19:50
hey @markismail7 , as far as I know on January 15th the first Stable build for Edge will be available for download, and we'll roll it out to Consumer soon after. The EdgeHTML Edge browser is getting replaced by Chromium Edge when this happens, but the actual EdgeHTML platform is still on users' machine s.t. stuff like WWA doesn't stop working. 

In terms of .NET, I hear ya. It's on our roadmap for WebView2 and we're definitely not leaving .NET developers behind. It's just that the .NET support will be based on our Win32 C++ control, so from a topological order, we need to get Win32 C++ first. Don't worry, it's on the way! Internally, we're figuring out when we can get a .NET preview out for developers to test on.

**Comment by chrisjshields** [comment] 2020-01-06 22:31
Will the Chromium Edge control support accessing the DOM tree using e.g. GetElementById as in the .Net IE WebBrowser control?

**Comment by liminzhu** [comment] 2020-01-06 23:06
// let's open another issue if we are going talk about this extensively

Currently not planning to add native methods for DOM manipulation but you can do the same through calling scripts. Would that work for you?

**Comment by markismail7** [comment] 2020-01-07 00:46
> hey @markismail7 , as far as I know on January 15th the first Stable build for Edge will be available for download, and we'll roll it out to Consumer soon after. The EdgeHTML Edge browser is getting replaced by Chromium Edge when this happens, but the actual EdgeHTML platform is still on users' machine s.t. stuff like WWA doesn't stop working.
> 
> In terms of .NET, I hear ya. It's on our roadmap for WebView2 and we're definitely not leaving .NET developers behind. It's just that the .NET support will be based on our Win32 C++ control, so from a topological order, we need to get Win32 C++ first. Don't worry, it's on the way! Internally, we're figuring out when we can get a .NET preview out for developers to test on.

Thanks for the reply. We just need a date on when .net will be included, so we can get ready. I'm tired of using Google Chrome. Nothing against google, but i love Microsoft. The reason we needed google   
chrome from the beginning is because any website that is build with Java Server pages will load slower on edge than Chrome. Everything Google uses is JSP. To me personally JSP is the slowest platform out there to build a website. Gmail is built with JSP, its takes forever to load on Chrome lol. I have 1Ghz internet speed and still takes time to load. That's why Google keep updating the splash screen for gmail lol. JSP belong in the Linux world. Thank God Amazon.com did not use JSP.  And I still couldn't believe Microsoft let Google take over all those years when it comes to the internet browser. I'm excited for the edge chromium to bring the balance back. And one more thing, i pray that Microsoft is working on an Email platform so we can leave Gmail too. We've been suffering with JSP Webpages since the beginning of Google. Again i still love Google, but i need the mother of computers ( Microsoft ) to take over again.

**Comment by liminzhu** [comment] 2020-01-08 02:17
Haha I love the passion in your reply @markismail7 .

We're currently targeting this March for a .NET preview. We (and I personally) really want to get this out ASAP but I do want to say though that there are other factors and work that can end up affecting our .NET scheduling.

**Comment by JNORMANAZ** [comment] 2020-01-24 22:32
I've been successfully been able to use WebView2 0.8.355 in a .Net Standard C# WPF Project.  I can't get it to do much, but this will work.
Reference the WebBrowser control on the form and name it.  
After InitializeComponent (or another appropriate place) use the Navigate method of the WebBrowser control instance.

**Comment by markismail7** [comment] 2020-01-24 23:27
Can you use invoke script?

**Comment by michael-russin** [comment] 2020-01-24 23:55
You can give this a try while you're waiting for the real .net WebView2 from Microsoft.   [.net WebView2](https://github.com/michael-russin/webview2-control)

**Comment by JNORMANAZ** [comment] 2020-01-27 16:02
@markismail7  I got as far as navigating!

**Comment by JNORMANAZ** [comment] 2020-01-27 17:02
@markismail7 Yes, I could.             BrowserWindowOne.NavigateToString("<script>alert('Hello world!');window.location.assign('https://www.microsoft.com');</script>");

**Comment by JNORMANAZ** [comment] 2020-01-27 17:30
@michael-russin  We may give it a try, thank  you.

**Comment by rscsharma** [comment] 2020-02-07 20:06
@michael-russin I have latest Edge Chromium installed (79.0.309.71). When I run WebView2.Wpf.Sample project, get the following exception. Any idea what might be causing this?

System.InvalidCastException: 'Unable to cast COM object of type 'System.__ComObject' to interface type 'MtrDev.WebView2.Interop.IWebView2Environment3'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D82C6A26-370F-4084-8149-C08FF1598C9B}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).'

**Comment by michael-russin** [comment] 2020-02-08 13:14
Thanks for taking a look at the sample.  That sample uses Microsoft.Web.WebView2.0.8.355 which requires Edge Chromium 80.   Try installing the beta version of Edge Chromium.   Also please post any other questions to [webview2-control](https://github.com/michael-russin/webview2-control/issues)

**Comment by ventodev93** [comment] 2020-02-12 12:55
Hi,
in my team we're starting a new project and would like the new webview2-control. As its availaibilty is planned for march we're considering to use the old webview for development purposes and would like to update as soon as the new version is released. 
Could you please give us a short info whether the migration from the old webview to the new one will be expensive or do we just have to change the nuget package?
Many Thanks in Advance!

**Comment by pagoe-msft** [comment] 2020-02-12 18:01
Hi @ventodev93,

1. By the old webview are you referring to the Edge HTML based WebView or the MS HTML based Browser Control?
2. What flavor of WebView are you planning to use? (Win32, UWP, .NET, ...)
3. How are you planning to use WebView in your application?

**Comment by ventodev93** [comment] 2020-02-26 05:38
Hi @pagoe-msft,
sry - I have not been in the office in the last days so my answer is delayed.

> Hi @ventodev93,
> 
> 1. By the old webview are you referring to the Edge HTML based WebView or the MS HTML based Browser Control?
=> We're using the Edge HTML based webview.
> 2. What flavor of WebView are you planning to use? (Win32, UWP, .NET, ...)
=> We're building a .NET Core 3.1/.NET 5 WPF-Application
> 3. How are you planning to use WebView in your application?
=> We're planning to use the WebView to host an Angular based SPA. The WPF-App handles the communication with our Hardware. So we'd like to set cookies of the Browser-Control.

Many Thanks in Advance for your Reply!

**Comment by noxo** [comment] 2020-03-12 10:17
will there be preview for UWP in March?

**Comment by applefanbois** [comment] 2020-04-02 12:39
Our UWP project is on hold because the old UWP Webview is 10 years behind Android and iOS/macOS. We cannot move further and are waiting for UWP Webview2. It is sad that MS decided to move backward with win32 instead of moving forward like the other companies. We are now telling our customers to move to Apple products if they cannot wait a year or more until MS provide the modern tools for modern applications. 

MS focusing on Win32 is telling the world : Our operating system will never be secure (sanboxed).

Our MS port will only have half of the features of our Android, iOS/macOS app. There is not even proper PDF viewer or PDF tools included in the MS SDK (the other os SDK do provide these features natively). So our Windows version will cost us thousands of dollars every year (for expensive pdf libs) just so we can provide basic PDF functionality like the other platforms.

**Comment by wjvii** [comment] 2020-04-02 17:05
I definitely wish that Microsoft would get this new viewer control to .NET developers and also make its pdf capabilities available in the same control. I use the new Edge for both web content and PDF content including filling and signing PDFs and it would be great to have that all directly available from Microsoft "out of the box" so to speak.

Hope we hear good news about a preview version soon.

**Comment by pagoe-msft** [comment] 2020-04-03 23:23
@applefanbois Shipping WebView2 on UWP is very important to us. You can checkout the alpha release here: https://docs.microsoft.com/en-us/uwp/toolkits/winui3/

@wjvii Stay tuned, we will have a WebView2 .NET Preview out soon!

**Comment by noxo** [comment] 2020-04-08 12:45
@pagoe-msft it seems that WinUI3 means, that whole UWP app needs to be ported use WinUI3 Xaml components. Are you planning to have any other paths to use WebView2 on exisintg UWP apps?

**Comment by wjvii** [comment] 2020-04-08 13:08
@pagoe-msft, very exciting, looking forward to it!

One thing I ran into yesterday was the need to be able to download or at least control the download of a file from a link in the page currently shown in the Webview, which I cannot do with the current Webview, or at least could not figure out how to. It appears the old Webbrowser control did allow you to hook into the download file event if I read some of the articles correctly. Will the new WebView2 control allow me to programmatically download a file or at least hook into the event when a file is being downloaded in the browser control? I have a scenario where I need to start that in a database vs a file on disk so that would be highly useful to replace the current save to a file and then import separately.

**Comment by applefanbois** [comment] 2020-04-08 13:12
We are doing that with the current Webview on Android, iOS and Win. but we trigger custom commands from server with javascript. We intercept and inject javascript within the Webview and obey our custom server commands to download and upload files.

**Comment by wjvii** [comment] 2020-04-08 19:19
@applefanbois Interesting approach and sounds super flexible. I am not very guru with the javascript or Typescript but some other members of our team are. Not sure this will work for us though because it sounds like you are saying you need access to the server side to create the custom commands, which I cannot do. Did I get that right?

**Comment by applefanbois** [comment] 2020-04-08 19:22
Yes, the server or the page loaded triggers javascript command that we intercept in our app and respond to it. We have bidirectional communication between the web page and WebView. If you need help, I can send you code. app.webview <-> webpage <-> server. Another way would be to override existing javascript function, for example to detect page name changes.

**Comment by antti-j** [comment] 2020-04-21 07:20
Now there is new Webview2 SDK version 0.9.488. That requires Edge 84.

I didn't see any mention about WPF. Is It so that Edge 85 is the earliest possible for some preview WPF support? Or still some hope for something in Edge 84?

**Comment by applefanbois** [comment] 2020-04-21 12:04
All I can say is that it does not work with a pure UWP project. The programmer in charge tried and told me we got an endless list of unsolvable errors. As of now, WebView2 on UWP is just hope. Maybe Microsoft is too busy cooking something special with Marina Abramović.

**Comment by pagoe-msft** [comment] 2020-05-20 04:19
Hi everyone,

We have released a preview of WebView2 for .NET! Check it out here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease

**Closed** 2020-05-20 04:19 UTC
Labels: feature request

**Comment by jameslin0312** [comment] 2020-05-20 06:14
Is there any .Net Core Getting Started Guide? By the way, in Widows from, CoreWebView2.CapturePreviewAsync has no callback handler parameter to be invoked when CapturePreview finishes writing to the stream.

**Comment by markismail7** [comment] 2020-05-20 13:47
> Hi everyone,
> 
> We have released a preview of WebView2 for .NET! Check it out here:
> https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease

I keep getting an error on load: Anyone knows why?
NullReferenceException: Object reference not set to an instance of an object.

**Comment by antti-j** [comment] 2020-05-20 15:05
> I keep getting an error on load: Anyone knows why?
> NullReferenceException: Object reference not set to an instance of an object.

Could the root cause be https://github.com/MicrosoftEdge/WebViewFeedback/issues/182

**Comment by markismail7** [comment] 2020-05-22 15:05
> > Hi everyone,
> > We have released a preview of WebView2 for .NET! Check it out here:
> > https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease
> 
> I keep getting an error on load: Anyone knows why?
> NullReferenceException: Object reference not set to an instance of an object.

I tried . It didn't work. here is the error:

System.InvalidOperationException: 'An error occurred creating the form. See Exception.InnerException 
  for details.  The error is: Object reference not set to an instance of an object.'

  NullReferenceException: Object reference not set to an instance of an object.

  This exception was originally thrown at this call stack:
  Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(System.EventArgs)
    System.Windows.Forms.Control.AssignParent(System.Windows.Forms.Control)
    System.Windows.Forms.Control.ControlCollection.Add(System.Windows.Forms.Control)
    System.Windows.Forms.Form.ControlCollection.Add(System.Windows.Forms.Control)
    Repair_.Form_test.InitializeComponent() in Form_test.Designer.vb

**Comment by ewyuen1999** [comment] 2020-05-22 16:16
I cannot even build a simple .NET Framework 4.7.2 app with it by installing the nuget package
Microsoft.Web.WebView2 0.9.488

Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0418	Assembly 'Microsoft.Web.WebView2.Wpf' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.	WpfWebView2	MainWindow.xaml	8	


<Window x:Class="WpfWebView2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfWebView2"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <DockPanel>
        <wv2:WebView2 Name="webView"
                      Source="https://www.microsoft.com"
        />
    </DockPanel>
</Window>

Any particular things I need to do beside install the nuget?

**Comment by david-risney** [comment] 2020-05-22 17:11
The .NET WebView2 is first available in [0.9.515-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.515-prerelease) and works with the latest [Edge canary channel browser](https://www.microsoftedgeinsider.com/en-us/download). Please make sure you're using these and if you're still hitting problems, please open a new issue. Thanks!

**Comment by markismail7** [comment] 2020-05-22 18:11
I found it lol for some reason you must change the name property. Change the Name property to webView.

**Comment by prasad-yadav** [comment] 2020-05-27 16:37
Hi everyone,
I had created a VSTO add-in project in that I had added on user control and add webview2 control on that and set source property. 
I want to load the webview2 control on that task pen but it will not work. I create a web view2 control event's like navigation started and completed but it will not trigger. I had used the latest canary version,  'webview2.winForms' and 'webview2.Core' library
I am trying to add WebView2Loader.dll but it will not be added to show the control in the toolbox so I added  'webview2.winForms.dll' so I get webview2 in the toolbox.

 

I get the following exception:
Object reference not set to an instance of an object.

 


************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TestWebView2.MyTaskPane.WorkaroundForm_Load(Object sender, EventArgs e) in
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ActiveXImpl.System.Windows.Forms.IWindowTarget.OnMessage(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by prasad-yadav** [comment] 2020-05-28 06:54
Hi Everyone,

When I tried to add the new webView2 control in VSTO (Word Add-In) project then it is throwing below error.


at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.AssignParent(Control value)
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at MyRibbonAddIn.Form1.InitializeComponent() in D:\Hitesh\MyRibbonAddIn\MyRibbonAddIn\Form1.Designer.cs:line 50
   at MyRibbonAddIn.Form1..ctor() in D:\Hitesh\MyRibbonAddIn\MyRibbonAddIn\Form1.cs:line 17
   at MyRibbonAddIn.MyRibbon.OnTaskPaneButton(IRibbonControl control) in D:\Hitesh\MyRibbonAddIn\MyRibbonAddIn\MyRibbon.cs:line 44


I have used the below configuration.

Webview2 library: The .NET WebView2  0.9.515-prerelease
.Net Framework: 4.6.2
Visual Studio 2015
Microsoft Edge (Chromium) Canary channel
Operating system: Windows 10

**Comment by prasad-yadav** [comment] 2020-05-28 08:38
Hi Everyone,

When I tried to add the new webView2 control in VSTO (Word Add-In) project then it is throwing below error.

at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
at System.Windows.Forms.Control.AssignParent(Control value)
at System.Windows.Forms.Control.ControlCollection.Add(Control value)
at System.Windows.Forms.Form.ControlCollection.Add(Control value)
at MyRibbonAddIn.Form1.InitializeComponent() in D:\Hitesh\MyRibbonAddIn\MyRibbonAddIn\Form1.Designer.cs:line 50
at MyRibbonAddIn.Form1..ctor() in D:\Hitesh\MyRibbonAddIn\MyRibbonAddIn\Form1.cs:line 17
at MyRibbonAddIn.MyRibbon.OnTaskPaneButton(IRibbonControl control) 

I have used the below configuration.

Webview2 library: The .NET WebView2 0.9.515-prerelease
.Net Framework: 4.6.2
Visual Studio 2015
Microsoft Edge (Chromium) Canary channel
Operating system: Windows 10

**Comment by prasad-yadav** [comment] 2020-05-28 08:40
Hi Everyone,

When I tried to add the new webView2 control in VSTO (Word Add-In) project then it is throwing below error.

at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
at System.Windows.Forms.Control.AssignParent(Control value)
at System.Windows.Forms.Control.ControlCollection.Add(Control value)
at System.Windows.Forms.Form.ControlCollection.Add(Control value)
at MyRibbonAddIn.Form1.InitializeComponent() in D:\Hitesh\MyRibbonAddIn\MyRibbonAddIn\Form1.Designer.cs:line 50
at MyRibbonAddIn.Form1..ctor()
at MyRibbonAddIn.MyRibbon.OnTaskPaneButton(IRibbonControl control)

I have used the below configuration.

Webview2 library: The .NET WebView2 0.9.515-prerelease
.Net Framework: 4.6.2
Visual Studio 2015
Microsoft Edge (Chromium) Canary channel
Operating system: Windows 10

**Comment by prasad-yadav** [comment] 2020-05-28 08:40
Hi Everyone,

When I tried to add the new webView2 control in VSTO (Word Add-In) project then it is throwing below error.

at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
at System.Windows.Forms.Control.AssignParent(Control value)
at System.Windows.Forms.Control.ControlCollection.Add(Control value)
at System.Windows.Forms.Form.ControlCollection.Add(Control value)
at MyRibbonAddIn.Form1.InitializeComponent() in 
at MyRibbonAddIn.Form1..ctor()
at MyRibbonAddIn.MyRibbon.OnTaskPaneButton(IRibbonControl control)

I have used the below configuration.

Webview2 library: The .NET WebView2 0.9.515-prerelease
.Net Framework: 4.6.2
Visual Studio 2015
Microsoft Edge (Chromium) Canary channel
Operating system: Windows 10

**Comment by brunofrance** [comment] 2020-06-22 13:18
Hi Everyone, I can't use WebView2 with .net core winform ; is it normal ? (it works with .net core wpf, but it's not what I use...)
Thanks

**Comment by mikemeinz** [comment] 2020-06-22 13:35
Use NuGet package version **0.9.538-prerelease.**  
Do not use NuGet package version **0.9.538**.

**Comment by markismail7** [comment] 2020-07-06 19:31
Microsoft: It has been 30 days and we still stock with the pre-release Webview2 for windows form. We have businesses to run. Release the production version already. Thanks.

**Comment by applefanbois** [comment] 2020-07-06 20:03
Same here our app is ready on iOS, macOS, Android... but we are stuck on Windows. We are warning our windows users that they won't get a newer version before another year. We tell them to buy Apple product if they want our latest features.

**Comment by liminzhu** [comment] 2020-07-07 16:50
Hey folks. To set the expectation, the .NET WebView2 is targeted for EoY. There are still some major blockers until we can GA this, e.g.

* [The evergreen WebView2 installer](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understand-the-webview2-runtime-and-installer-preview) that allows the developer to programmatically install the WebView web platform without installing the browser. 
* The .NET API itself is still new and not stable. There will potentially be some API renaming and other breaking change while we're still in preview.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap
